extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - prettier
  - simple-import-sort
root: true
rules:
  prettier/prettier: error
  simple-import-sort/imports: error
  simple-import-sort/exports: error
